<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Eccube\Entity\Banner;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * BannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Banner::class);
    }

    /**
     * バナー覧を取得する.
     *
     * @return Banner[] バナーの配列
     */
    public function getList()
    {
        $qb = $this->createQueryBuilder('b')->orderBy('b.device', 'ASC')->addOrderBy('b.sort', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function getListBannerSliders()
    {
        $qb = $this->createQueryBuilder('b')->where('b.type = 1')->orderBy('b.device', 'ASC')->addOrderBy('b.sort', 'ASC');

        return $qb->getQuery()->getResult();
    }

    public function getListBannerTopSPs()
    {
        $qb = $this->createQueryBuilder('b')->where('b.type = 2')->orderBy('b.device', 'ASC')->addOrderBy('b.sort', 'ASC');

        return $qb->getQuery()->getResult();
    }

    /**
     * バナー覧を取得する.
     *
     * @return Banner[] バナーの配列
     */
    public function getCampaignBanner()
    {
        $qb = $this->createQueryBuilder('b')->where('b.type = 2')->andWhere('b.status = 1')->orderBy('b.id', 'ASC');

        return count($qb->getQuery()->getResult()) > 0 ? $qb->getQuery()->getResult() : null;
    }

    /**
     * バナー覧を取得する.
     *
     * @return Banner[] バナーの配列
     */
    public function getHeaderBannerPC()
    {
        $qb = $this->createQueryBuilder('b')->where('b.type = 1')->andWhere('b.device = 1')->andWhere('b.status = 1')->orderBy('b.sort', 'ASC');

        return count($qb->getQuery()->getResult()) > 0 ? $qb->getQuery()->getResult() : null;
    }

    /**
     * バナー覧を取得する.
     *
     * @return Banner[] バナーの配列
     */
    public function getHeaderBannerSP()
    {
        $qb = $this->createQueryBuilder('b')->where('b.type = 1')->andWhere('b.device = 2')->andWhere('b.status = 1')->orderBy('b.sort', 'ASC');

        return count($qb->getQuery()->getResult()) > 0 ? $qb->getQuery()->getResult() : null;
    }
}