<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Eccube\Repository;

use Eccube\Entity\Holiday;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * HolidayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HolidayRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Holiday::class);
    }

    /**
     * 祝日覧を取得する.
     *
     * @return Holiday[] 祝日の配列
     */
    public function getList()
    {
        $qb = $this->createQueryBuilder('ld')->addOrderBy('ld.date', 'ASC');

        return $qb->getQuery()->getResult();
    }

    /**
     * 祝日覧を取得する.
     *
     * @return Holiday[] 祝日の配列
     */
    public function getArrayHoliday()
    {
        $qb = $this->createQueryBuilder('ld')->addOrderBy('ld.date', 'ASC');

        $holidays = $qb->getQuery()->getResult();
        $arrDate = [];

        foreach ($holidays as $holiday) {
            $arrDate[] = $holiday->getDate()->format('n/j');
        }

        return json_encode($arrDate);
    }
}